# Travis example for Identifier created by Rafael Garibotti

sudo: true
language: c
compiler:
  - gcc
  before_install:
  - sudo apt-get -y install cppcheck
  - sudo apt-get -y install valgrind  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd identifier; make
#  - make test
